### PR TITLE
Indicate Tech Preview on OIDC v2 sections

### PR DESCRIPTION
**Pull request by creatornader**
Wanted to update the readme ahead of our public MATTR Pi Product launch because there will be more visitors -- we should indicate the sections of the readme which are related to OpenID4VCI 2.0 and are currently only available in tech preview mode. We also want to start using "MATTR Wallet Toolkit" instead of "MATTR Wallet SDK" so updated to reflect that.

### CODE REVIEW

**Comment by creatornader** [comment]
Perhaps we consider renaming the repo itself to `docs-wallet-toolkit` as well? Just wary of cascading effects and other collateral that might reference the repo. Then again, I'm pretty sure the NPM package is/has already been renamed to reflect the change, so maybe we should pull the trigger on this too. Thoughts @luke-dotcom and others?

**Review by dylan-paul — CHANGES_REQUESTED** [review]
Hey @creatornader, The only part going into (Tech Preview) is the OpenID Issuance - the others are standard.

**Comment by creatornader** [comment]
Updated @dylan-paul, let me know what you think.

**Review by dylan-paul — DISMISSED** [review]
LGTM

**Comment by creatornader** [comment]
Also I've noticed all the .md files also reference "MATTR Wallet SDK" when they should be "MATTR Wallet Toolkit". Looks like the files were all generated by the MATTR ci as well, so not sure how to best handle that. Anybody from @mattrglobal/engineering that can help out here?

**Comment by creatornader** [comment]
Opened up a separate PR on https://github.com/mattrglobal/wallet-sdk so closing this one

**Pull request closed without merging**
